import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, Save, Truck, Flag, Gem, ShieldCheck } from "lucide-react";
import AdminSidebar from "./AdminSidebar";
import { apiRequest } from "../../services/api";
import "./AdminContent.css";

interface BenefitConfig { id:string; icon:string; title:{en:string;es:string}; description:{en:string;es:string}; active:boolean; order:number; }
const fallbackBenefits:BenefitConfig[]=[
{id:"fast-shipping",icon:"truck",title:{en:"Fast Shipping",es:"Envío rápido"},description:{en:"5 to 7 business days directly to your door.",es:"De 5 a 7 días hábiles directamente hasta tu puerta."},active:true,order:1},
{id:"made-usa",icon:"flag",title:{en:"Made in USA",es:"Hecho en EE. UU."},description:{en:"Proudly made in the United States.",es:"Orgullosamente hecho en Estados Unidos."},active:true,order:2},
{id:"premium-quality",icon:"gem",title:{en:"Premium Quality",es:"Calidad premium"},description:{en:"Premium materials and craftsmanship.",es:"Materiales premium y excelente fabricación."},active:true,order:3},
{id:"secure-checkout",icon:"shield-check",title:{en:"Secure Checkout",es:"Pago seguro"},description:{en:"100% secure payments with trusted providers.",es:"Pagos 100% seguros con proveedores de confianza."},active:true,order:4}];
const iconFor=(icon:string)=>icon==="truck"?<Truck size={26}/>:icon==="flag"?<Flag size={26}/>:icon==="gem"?<Gem size={26}/>:<ShieldCheck size={26}/>;

const AdminContent=()=>{
 const[benefits,setBenefits]=useState<BenefitConfig[]>(fallbackBenefits); const[enabled,setEnabled]=useState(true); const[loading,setLoading]=useState(true); const[saving,setSaving]=useState(false);
 useEffect(()=>{void(async()=>{try{const r=await apiRequest<{settings:{config?:{benefits?:BenefitConfig[];benefitsEnabled?:boolean}}}>("/api/settings?app_refresh="+Date.now(),{cache:"no-store"});const loaded=r.settings?.config?.benefits;if(Array.isArray(loaded)&&loaded.length)setBenefits(loaded);if(typeof r.settings?.config?.benefitsEnabled==="boolean")setEnabled(r.settings.config.benefitsEnabled);}catch(e){console.error(e)}finally{setLoading(false)}})()},[]);
 const save=async()=>{setSaving(true);try{const r=await apiRequest<{settings:{config?:Record<string,unknown>;websiteName?:string;browserTitle?:string}}>("/api/settings?app_refresh="+Date.now(),{cache:"no-store"});await apiRequest("/api/settings",{method:"PUT",body:JSON.stringify({websiteName:r.settings?.websiteName,browserTitle:r.settings?.browserTitle,config:{...(r.settings?.config||{}),benefits,benefitsEnabled:enabled}})});window.dispatchEvent(new Event("mtd-site-config-updated"));alert("Homepage Content saved successfully.")}catch(e){console.error(e);alert(e instanceof Error?e.message:"Unable to save homepage content.")}finally{setSaving(false)}};
 return <div className="admin-content-layout"><AdminSidebar username="Administrator"/><main className="admin-content-page"><header className="admin-content-header"><div><span className="admin-content-eyebrow">Website Content</span><h1>Content</h1><p>Manage homepage content as one block. The four benefit cards stay together.</p></div></header><section className="admin-content-panel admin-benefits-panel"><div className="admin-content-panel-head"><div><strong>Homepage Benefit Cards</strong><span>4 fixed cards · one shared setting · shown on the homepage</span></div><button className="admin-content-primary" onClick={()=>void save()} disabled={saving||loading}>{saving?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>} {saving?"Saving…":"Save content"}</button></div>{loading?<div className="admin-content-loading"><LoaderCircle className="spin"/> Loading homepage content…</div>:<div className="admin-benefits-single"><label className="admin-benefits-global-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span><strong>Show all four cards</strong><small>This single setting applies to the complete four-card block.</small></span><CheckCircle2 size={22}/></label><div className="admin-benefits-preview-grid">{benefits.slice().sort((a,b)=>a.order-b.order).slice(0,4).map(b=><article className="admin-benefit-card" key={b.id}><div className="admin-benefit-preview"><div className="admin-benefit-preview-icon">{iconFor(b.icon)}</div><div><strong>{b.title.en}</strong><span>{b.description.en}</span></div></div></article>)}</div></div>}</section></main></div>;
};
export default AdminContent;