import { createContext, useContext, useEffect, useRef, useState } from "react";
import { Building2, Globe, Settings, Upload, Trash2, Plus, ChevronUp, ChevronDown, Save, Link2, UserRound, Share2, LayoutTemplate, ChevronDown as Expand, ChevronUp as Collapse, X, Check } from "lucide-react";
import AdminSidebar from "./AdminSidebar";
import { apiRequest } from "../../services/api";
import "./AdminSettings.css";

type LocalizedText={en:string;es:string};
type HeroSlide={id:string;image:string;background:string;order:number;active:boolean;title:LocalizedText;subtitle:LocalizedText;primaryButton:LocalizedText;primaryLink:string;secondaryButton:LocalizedText;secondaryLink:string};
type NavLink={id:string;label:LocalizedText;path:string;active:boolean;order:number};
type FooterSection={id:string;title:LocalizedText;links:NavLink[];active:boolean;order:number};
type SocialLink={id:string;name:string;url:string;active:boolean;order:number};
type PageConfig={id:string;title:LocalizedText;slug:string;body:LocalizedText;active:boolean};
type SiteConfig={slogan:LocalizedText;designerName:LocalizedText;designerTitle:LocalizedText;designerBio:LocalizedText;businessPhone:string;businessAddress:string;heroSlides:HeroSlide[];headerLinks:NavLink[];footerSections:FooterSection[];socialLinks:SocialLink[];pages:PageConfig[]};
type SettingsData={websiteName:string;browserTitle:string;slogan:string;logoUrl:string|null;supportEmail:string;notificationsEnabled:boolean;config:SiteConfig};
type SectionKey="branding"|"hero"|"header"|"footer"|"social"|"designer";

type SettingsSectionContextValue={open:Record<SectionKey,boolean>;status:Partial<Record<SectionKey,string>>;saving:SectionKey|null;toggle:(key:SectionKey)=>void;saveSection:(key:SectionKey)=>void};
const SettingsSectionContext=createContext<SettingsSectionContextValue|null>(null);
const emptyText=():LocalizedText=>({en:"",es:""});
const emptyHero=(order:number):HeroSlide=>({id:`hero-${Date.now()}`,image:"",background:"/images/hero/hero-background.jpg",order,active:true,title:emptyText(),subtitle:emptyText(),primaryButton:emptyText(),primaryLink:"/customize",secondaryButton:emptyText(),secondaryLink:"/products"});
const emptyLink=(order:number):NavLink=>({id:`link-${Date.now()}`,label:emptyText(),path:"/",active:true,order});
const emptyPage=():PageConfig=>({id:`page-${Date.now()}`,title:emptyText(),slug:"new-page",body:emptyText(),active:true});
const syncPublicConfig=(config:SiteConfig)=>{try{localStorage.setItem("mtd_site_config",JSON.stringify(config));window.dispatchEvent(new Event("mtd-site-config-updated"));}catch{}};
const settingsRequestOptions={cache:"no-store" as RequestCache};

function SettingsSection({id,icon,title,kicker,children,add}:{id:SectionKey;icon:React.ReactNode;title:string;kicker:string;children:React.ReactNode;add?:React.ReactNode}){const ctx=useContext(SettingsSectionContext);if(!ctx)return null;const {open,status,saving,toggle,saveSection}=ctx;return <section className={`admin-settings__section ${open[id]?"is-open":""}`}><div className="admin-settings__section-head"><button className="admin-settings__section-toggle" onClick={()=>toggle(id)} type="button"><span className="admin-settings__section-icon">{icon}</span><span className="admin-settings__section-title"><small>{kicker}</small><strong>{title}</strong></span><span className="admin-settings__chevron">{open[id]?<Collapse size={20}/>:<Expand size={20}/>}</span></button>{add&&<div className="admin-settings__head-add">{add}</div>}</div>{open[id]&&<div className="admin-settings__section-body">{children}<div className="admin-settings__section-actions"><span className={status[id]?.startsWith("✓")?"success":"section-status"}>{status[id]}</span><button className="admin-settings__update" onClick={()=>saveSection(id)} disabled={saving!==null}><Save size={17}/>{saving===id?"Actualizando…":"Actualizar"}</button></div></div>}</section>}

function AdminSettings(){
 const [currentUser,setCurrentUser]=useState<{username:string}|null>(null);const [settings,setSettings]=useState<SettingsData|null>(null);const [websiteName,setWebsiteName]=useState("");const [browserTitle,setBrowserTitle]=useState("");const [logoUrl,setLogoUrl]=useState("");const [supportEmail,setSupportEmail]=useState("");const [notificationsEnabled,setNotificationsEnabled]=useState(true);const [open,setOpen]=useState<Record<SectionKey,boolean>>({branding:false,hero:false,header:false,footer:false,social:false,designer:false});const [saving,setSaving]=useState<SectionKey|null>(null);const [status,setStatus]=useState<Partial<Record<SectionKey,string>>>({});const [message,setMessage]=useState("");const [pendingLogo,setPendingLogo]=useState<File|null>(null);const [logoPreview,setLogoPreview]=useState("");const [heroUploading,setHeroUploading]=useState<number|null>(null);const fileRef=useRef<HTMLInputElement>(null);const heroFileRef=useRef<HTMLInputElement>(null);const heroUploadIndex=useRef<number|null>(null);
 useEffect(()=>{apiRequest<{status:string;user:{username:string}}>("/api/user/me").then(r=>setCurrentUser(r.user)).catch(()=>{});apiRequest<{status:string;settings:SettingsData}>(`/api/settings?settings_refresh=${Date.now()}`,settingsRequestOptions).then(r=>{setSettings(r.settings);setWebsiteName(r.settings.websiteName);setBrowserTitle(r.settings.browserTitle);setLogoUrl(r.settings.logoUrl??"");try{if(r.settings.logoUrl)localStorage.setItem("mtd_logo_url",r.settings.logoUrl);else localStorage.removeItem("mtd_logo_url");}catch{}setSupportEmail(r.settings.supportEmail);setNotificationsEnabled(r.settings.notificationsEnabled);syncPublicConfig(r.settings.config);}).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load settings."));},[]);
 const config=settings?.config;const updateConfig=(patch:Partial<SiteConfig>)=>setSettings(prev=>prev?({...prev,config:{...prev.config,...patch}}):prev);const toggle=(key:SectionKey)=>setOpen(prev=>({...prev,[key]:!prev[key]}));const updateStatus=(key:SectionKey,text:string)=>setStatus(prev=>({...prev,[key]:text}));
 const updateHero=(i:number,p:Partial<HeroSlide>)=>{if(!config)return;const a=[...config.heroSlides];a[i]={...a[i],...p};updateConfig({heroSlides:a})};const moveHero=(i:number,d:-1|1)=>{if(!config)return;const n=i+d;if(n<0||n>=config.heroSlides.length)return;const a=[...config.heroSlides];[a[i],a[n]]=[a[n],a[i]];updateConfig({heroSlides:a.map((x,j)=>({...x,order:j+1}))})};const removeHero=(i:number)=>{if(!config)return;updateConfig({heroSlides:config.heroSlides.filter((_,j)=>j!==i).map((x,j)=>({...x,order:j+1}))})};
 const updateHeader=(i:number,p:Partial<NavLink>)=>{if(!config)return;const a=[...config.headerLinks];a[i]={...a[i],...p};updateConfig({headerLinks:a})};const removeHeader=(i:number)=>{if(!config)return;updateConfig({headerLinks:config.headerLinks.filter((_,j)=>j!==i).map((x,j)=>({...x,order:j+1}))})};
 const updateFooter=(i:number,p:Partial<FooterSection>)=>{if(!config)return;const a=[...config.footerSections];a[i]={...a[i],...p};updateConfig({footerSections:a})};const updateFooterLink=(si:number,li:number,p:Partial<NavLink>)=>{if(!config)return;const a=[...config.footerSections],links=[...a[si].links];links[li]={...links[li],...p};a[si]={...a[si],links};updateConfig({footerSections:a})};const removeFooterLink=(si:number,li:number)=>{if(!config)return;const a=[...config.footerSections];a[si]={...a[si],links:a[si].links.filter((_,j)=>j!==li).map((x,j)=>({...x,order:j+1}))};updateConfig({footerSections:a})};const addFooterSection=()=>{if(config)updateConfig({footerSections:[...config.footerSections,{id:`footer-${Date.now()}`,title:emptyText(),active:true,order:config.footerSections.length+1,links:[]}]})};const removeFooterSection=(i:number)=>{if(config)updateConfig({footerSections:config.footerSections.filter((_,j)=>j!==i).map((x,j)=>({...x,order:j+1}))})};
 const updateSocial=(i:number,p:Partial<SocialLink>)=>{if(!config)return;const a=[...config.socialLinks];a[i]={...a[i],...p};updateConfig({socialLinks:a})};const removeSocial=(i:number)=>{if(config)updateConfig({socialLinks:config.socialLinks.filter((_,j)=>j!==i).map((x,j)=>({...x,order:j+1}))})};const updatePage=(i:number,p:Partial<PageConfig>)=>{if(!config)return;const a=[...config.pages];a[i]={...a[i],...p};updateConfig({pages:a})};const removePage=(i:number)=>{if(config)updateConfig({pages:config.pages.filter((_,j)=>j!==i)})};
 const chooseLogo=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!["image/png","image/jpeg","image/webp"].includes(f.type)){setMessage("Logo must be PNG, JPEG or WebP.");return}if(f.size>5*1024*1024){setMessage("Logo must be 5 MB or smaller.");return}if(logoPreview)URL.revokeObjectURL(logoPreview);setPendingLogo(f);setLogoPreview(URL.createObjectURL(f));setMessage("Logo preview ready. Accept it, then select Update Branding to save it.");if(fileRef.current)fileRef.current.value=""};const cancelLogo=()=>{if(logoPreview)URL.revokeObjectURL(logoPreview);setPendingLogo(null);setLogoPreview("")};const acceptLogo=()=>{if(pendingLogo)setMessage("New logo accepted for this update.")};const removeLogo=()=>{if(!logoUrl&&!pendingLogo)return;if(!window.confirm("Remove the current logo? This will be saved when you update Branding."))return;cancelLogo();setLogoUrl("");setMessage("Logo marked for removal. Update Branding to apply it.")};
 const chooseHeroImage=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];const i=heroUploadIndex.current;heroUploadIndex.current=null;if(heroFileRef.current)heroFileRef.current.value="";if(!f||i===null)return;if(!["image/png","image/jpeg","image/webp"].includes(f.type)){setMessage("Hero image must be PNG, JPEG or WebP.");return}if(f.size>5*1024*1024){setMessage("Hero image must be 5 MB or smaller.");return}try{setHeroUploading(i);setMessage(`Subiendo imagen del Slider ${i+1}…`);const fd=new FormData();fd.append("image",f);const u=await apiRequest<{image_url:string}>("/api/upload/hero",{method:"POST",body:fd});updateHero(i,{image:u.image_url});updateStatus("hero",`✓ Imagen del Slider ${i+1} lista. Pulsa Actualizar para publicarla.`);setMessage("Imagen subida correctamente. Se ajustará automáticamente al Hero.")}catch(err){setMessage(err instanceof Error?err.message:"Unable to upload hero image.")}finally{setHeroUploading(null)}};
 const openHeroPicker=(i:number)=>{heroUploadIndex.current=i;heroFileRef.current?.click()};const clearHeroImage=(i:number)=>{if(!config)return;if(!config.heroSlides[i]?.image)return;if(!window.confirm(`¿Eliminar la imagen del Slider ${i+1}?`))return;updateHero(i,{image:""});updateStatus("hero","Imagen marcada para eliminar. Pulsa Actualizar para aplicar el cambio.")};
 const saveSection=async(key:SectionKey)=>{if(!settings||!config)return;try{setSaving(key);setMessage("");updateStatus(key,"");let finalLogo=logoUrl||null;if(key==="branding"&&pendingLogo){const fd=new FormData();fd.append("image",pendingLogo);const u=await apiRequest<{image_url:string}>("/api/upload/logo",{method:"POST",body:fd});finalLogo=u.image_url;setLogoUrl(u.image_url);cancelLogo()}const patch:Partial<SiteConfig>=key==="branding"?{businessPhone:config.businessPhone,businessAddress:config.businessAddress,slogan:config.slogan}:key==="hero"?{heroSlides:config.heroSlides}:key==="header"?{headerLinks:config.headerLinks,pages:config.pages}:key==="footer"?{footerSections:config.footerSections,businessPhone:config.businessPhone}:key==="social"?{socialLinks:config.socialLinks}:{designerName:config.designerName,designerTitle:config.designerTitle,designerBio:config.designerBio};const r=await apiRequest<{status:string;settings:SettingsData}>("/api/settings",{method:"PUT",body:JSON.stringify({websiteName,browserTitle,logoUrl:finalLogo,supportEmail,notificationsEnabled,config:patch})});const v=r.settings;setSettings(v);setWebsiteName(v.websiteName);setBrowserTitle(v.browserTitle);setLogoUrl(v.logoUrl??"");try{if(v.logoUrl)localStorage.setItem("mtd_logo_url",v.logoUrl);else localStorage.removeItem("mtd_logo_url");}catch{}setSupportEmail(v.supportEmail);setNotificationsEnabled(v.notificationsEnabled);syncPublicConfig(v.config);updateStatus(key,"✓ Cambios guardados");setMessage("Cambios guardados y verificados en el servidor.")}catch(e){updateStatus(key,"No se pudo guardar");setMessage(e instanceof Error?e.message:"Unable to save settings.")}finally{setSaving(null)}};
 if(!settings||!config)return <><AdminSidebar username={currentUser?.username||"Administrator"}/><main className="admin-settings"><div className="admin-settings__loading">Loading Settings…</div></main></>;
 const Section=SettingsSection;const contextValue={open,status,saving,toggle,saveSection};const supportSectionIndex=config.footerSections.findIndex(s=>s.id==="footer-support");const resolvedSupportIndex=supportSectionIndex>=0?supportSectionIndex:Math.min(2,Math.max(0,config.footerSections.length-1));const supportSection=config.footerSections[resolvedSupportIndex];const whatsappIndex=supportSection?.links.findIndex(l=>String(l.label?.en??"").trim().toLowerCase()==="whatsapp")??-1;const whatsappUrl=whatsappIndex>=0?supportSection.links[whatsappIndex].path:"https://wa.me/qr/6FQZEC7MEQN3N1";const updateWhatsappUrl=(url:string)=>{if(!config||!supportSection)return;if(whatsappIndex>=0){updateFooterLink(resolvedSupportIndex,whatsappIndex,{path:url});return}updateFooter(resolvedSupportIndex,{links:[...supportSection.links,{id:`whatsapp-${Date.now()}`,label:{en:"WhatsApp",es:"WhatsApp"},path:url,active:true,order:supportSection.links.length+1}]})};const qrPreview=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(whatsappUrl)}`;
 return <div className="admin-layout"><AdminSidebar username={currentUser?.username||"Administrator"}/><main className="admin-settings"><section className="admin-settings__hero"><div><span>ADMINISTRATION</span><h1>Settings</h1><p>Manage the public website section by section. Each update is saved and verified independently.</p></div><Settings size={42}/></section><section className="admin-settings__container">{message&&<div className="admin-settings__message">{message}<button onClick={()=>setMessage("")}><X size={16}/></button></div>}<SettingsSectionContext.Provider value={contextValue}>
 <Section id="branding" icon={<Building2/>} kicker="BRANDING" title="Business & Website"><div className="admin-settings__grid"><label>Store Name<input value={websiteName} onChange={e=>setWebsiteName(e.target.value)}/></label><label>Browser Title<input value={browserTitle} onChange={e=>setBrowserTitle(e.target.value)}/></label><label>Support Email<input type="email" value={supportEmail} onChange={e=>setSupportEmail(e.target.value)}/></label><label>Business Phone<input value={config.businessPhone} onChange={e=>updateConfig({businessPhone:e.target.value})}/></label><label>Business Address<input value={config.businessAddress} onChange={e=>updateConfig({businessAddress:e.target.value})}/></label><label>Slogan (English)<input value={config.slogan.en} onChange={e=>updateConfig({slogan:{en:e.target.value,es:config.slogan.es}})}/></label></div><div className="admin-settings__logo-card"><div><strong>Website Logo</strong><p>PNG, JPEG or WebP · max 5 MB</p></div><div className="admin-settings__logo-row">{(logoPreview||logoUrl)&&<img src={logoPreview||logoUrl} alt="Logo preview"/>}<input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={chooseLogo}/><button type="button" onClick={()=>fileRef.current?.click()}><Upload size={17}/> Seleccionar</button>{pendingLogo&&<><button className="secondary" type="button" onClick={acceptLogo}><Check size={17}/> Aceptar</button><button className="secondary" type="button" onClick={cancelLogo}>Cancelar</button></>}{logoUrl&&!pendingLogo&&<button className="danger" type="button" onClick={removeLogo}><Trash2 size={17}/> Eliminar</button>}</div></div><label className="admin-settings__toggle"><input type="checkbox" checked={notificationsEnabled} onChange={e=>setNotificationsEnabled(e.target.checked)}/> Administrative notifications enabled</label></Section>
 <Section id="hero" icon={<LayoutTemplate/>} kicker="HOME" title="Hero Slider" add={<button className="admin-settings__add" onClick={()=>updateConfig({heroSlides:[...config.heroSlides,emptyHero(config.heroSlides.length+1)]})}><Plus size={17}/> Add Slider</button>}><input ref={heroFileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={chooseHeroImage}/><div className="admin-settings__list">{config.heroSlides.map((s,i)=><article className="admin-settings__item" key={s.id}><div className="admin-settings__item-top"><strong>Slider {i+1}</strong><div><button onClick={()=>moveHero(i,-1)} disabled={i===0}><ChevronUp/></button><button onClick={()=>moveHero(i,1)} disabled={i===config.heroSlides.length-1}><ChevronDown/></button><button className="danger" onClick={()=>removeHero(i)}><Trash2/></button></div></div><div className="admin-settings__hero-image-card"><div className="admin-settings__hero-image-preview">{s.image?<img src={s.image} alt={`Hero Slider ${i+1}`}/>:<span>No hero image selected</span>}</div><div className="admin-settings__hero-image-actions"><div><strong>Hero Product Image</strong><p>Sube una imagen y el sitio la ajustará automáticamente sin deformarla.</p></div><div className="admin-settings__logo-row"><button type="button" onClick={()=>openHeroPicker(i)} disabled={heroUploading===i}><Upload size={17}/>{heroUploading===i?"Subiendo…":s.image?"Reemplazar imagen":"Subir imagen"}</button>{s.image&&<button className="danger" type="button" onClick={()=>clearHeroImage(i)}><Trash2 size={17}/> Eliminar imagen</button>}</div></div></div><div className="admin-settings__grid"><label>Image URL<input value={s.image} placeholder="Upload an image above or paste a URL" onChange={e=>updateHero(i,{image:e.target.value})}/></label><label>Background URL<input value={s.background} onChange={e=>updateHero(i,{background:e.target.value})}/></label><label>Title (English)<textarea value={s.title.en} onChange={e=>updateHero(i,{title:{...s.title,en:e.target.value}})}/></label><label>Subtitle (English)<textarea value={s.subtitle.en} onChange={e=>updateHero(i,{subtitle:{...s.subtitle,en:e.target.value}})}/></label><label>Primary Button<input value={s.primaryButton.en} onChange={e=>updateHero(i,{primaryButton:{...s.primaryButton,en:e.target.value}})}/></label><label>Primary Link<input value={s.primaryLink} onChange={e=>updateHero(i,{primaryLink:e.target.value})}/></label><label>Secondary Button<input value={s.secondaryButton.en} onChange={e=>updateHero(i,{secondaryButton:{...s.secondaryButton,en:e.target.value}})}/></label><label>Secondary Link<input value={s.secondaryLink} onChange={e=>updateHero(i,{secondaryLink:e.target.value})}/></label><label className="admin-settings__toggle"><input type="checkbox" checked={s.active} onChange={e=>updateHero(i,{active:e.target.checked})}/> Active</label></div></article>)}</div></Section>
 <Section id="header" icon={<Link2/>} kicker="HEADER" title="Navigation & Pages" add={<button className="admin-settings__add" onClick={()=>updateConfig({headerLinks:[...config.headerLinks,emptyLink(config.headerLinks.length+1)]})}><Plus size={17}/> Add Navigation</button>}><div className="admin-settings__list">{config.headerLinks.map((l,i)=><article className="admin-settings__compact" key={l.id}><input value={l.label.en} placeholder="Page name" onChange={e=>updateHeader(i,{label:{...l.label,en:e.target.value}})}/><input value={l.path} placeholder="/path" onChange={e=>updateHeader(i,{path:e.target.value})}/><label><input type="checkbox" checked={l.active} onChange={e=>updateHeader(i,{active:e.target.checked})}/> Active</label><button className="danger" onClick={()=>removeHeader(i)}><Trash2/></button></article>)}</div><div className="admin-settings__subhead"><div><small>PUBLIC PAGES</small><strong>Page Content</strong></div><button className="admin-settings__add" onClick={()=>updateConfig({pages:[...config.pages,emptyPage()]})}><Plus size={17}/> Add Page</button></div><div className="admin-settings__list">{config.pages.map((p,i)=><article className="admin-settings__item" key={p.id}><div className="admin-settings__item-top"><strong>Page {i+1}</strong><button className="danger" onClick={()=>removePage(i)}><Trash2/></button></div><div className="admin-settings__grid"><label>Title (English)<input value={p.title.en} onChange={e=>updatePage(i,{title:{...p.title,en:e.target.value}})}/></label><label>Slug<input value={p.slug} onChange={e=>updatePage(i,{slug:e.target.value.replace(/^\//,"")})}/></label><label className="full">Body (English)<textarea value={p.body.en} onChange={e=>updatePage(i,{body:{...p.body,en:e.target.value}})}/></label><label className="admin-settings__toggle"><input type="checkbox" checked={p.active} onChange={e=>updatePage(i,{active:e.target.checked})}/> Active</label></div></article>)}</div></Section>
 <Section id="footer" icon={<Globe/>} kicker="FOOTER" title="Footer Sections & Pages" add={<button className="admin-settings__add" onClick={addFooterSection}><Plus size={17}/> Add Section</button>}><div className="admin-settings__card admin-settings__footer-contact-card"><div><small>WHATSAPP / QR</small><strong>Footer contact</strong><p>Edit the phone number and WhatsApp destination used by the QR in the public footer.</p></div><div className="admin-settings__grid"><label>WhatsApp / QR Link<input value={whatsappUrl} onChange={e=>updateWhatsappUrl(e.target.value)} placeholder="https://wa.me/..."/></label><label>WhatsApp Phone Number<input value={config.businessPhone} onChange={e=>updateConfig({businessPhone:e.target.value})}/></label></div><div className="admin-settings__qr-preview"><img src={qrPreview} alt="WhatsApp QR preview"/><span>QR preview updates from the link above.</span></div></div><div className="admin-settings__list">{config.footerSections.map((s,si)=><article className="admin-settings__item" key={s.id}><div className="admin-settings__item-top"><strong><input value={s.title.en} onChange={e=>updateFooter(si,{title:{...s.title,en:e.target.value}})}/></strong><button className="danger" onClick={()=>removeFooterSection(si)}><Trash2/></button></div>{s.links.map((l,li)=><div className="admin-settings__compact" key={l.id}><input value={l.label.en} onChange={e=>updateFooterLink(si,li,{label:{...l.label,en:e.target.value}})}/><input value={l.path} onChange={e=>updateFooterLink(si,li,{path:e.target.value})}/><label><input type="checkbox" checked={l.active} onChange={e=>updateFooterLink(si,li,{active:e.target.checked})}/> Active</label><button className="danger" onClick={()=>removeFooterLink(si,li)}><Trash2/></button></div>)}<button className="admin-settings__inline-add" onClick={()=>updateFooter(si,{links:[...s.links,emptyLink(s.links.length+1)]})}><Plus size={16}/> Add Page to Section</button></article>)}</div></Section>
 <Section id="social" icon={<Share2/>} kicker="SOCIAL" title="Social Networks" add={<button className="admin-settings__add" onClick={()=>updateConfig({socialLinks:[...config.socialLinks,{id:`social-${Date.now()}`,name:"New Network",url:"",active:true,order:config.socialLinks.length+1}]})}><Plus size={17}/> Add Network</button>}><div className="admin-settings__list">{config.socialLinks.map((s,i)=><article className="admin-settings__compact" key={s.id}><input value={s.name} onChange={e=>updateSocial(i,{name:e.target.value})}/><input value={s.url} placeholder="https://" onChange={e=>updateSocial(i,{url:e.target.value})}/><label><input type="checkbox" checked={s.active} onChange={e=>updateSocial(i,{active:e.target.checked})}/> Active</label><button className="danger" onClick={()=>removeSocial(i)}><Trash2/></button></article>)}</div></Section>
 <Section id="designer" icon={<UserRound/>} kicker="DESIGNER" title="Public Designer Information"><div className="admin-settings__grid"><label>Name (English)<input value={config.designerName.en} onChange={e=>updateConfig({designerName:{...config.designerName,en:e.target.value}})}/></label><label>Title (English)<input value={config.designerTitle.en} onChange={e=>updateConfig({designerTitle:{...config.designerTitle,en:e.target.value}})}/></label><label className="full">Bio (English)<textarea value={config.designerBio.en} onChange={e=>updateConfig({designerBio:{...config.designerBio,en:e.target.value}})}/></label></div></Section>
 </SettingsSectionContext.Provider></section></main></div>;
}
export default AdminSettings;
