import { useCallback, useEffect, useMemo, useState } from "react";
import { Calendar, ChevronLeft, ChevronRight, Eye, RefreshCw, Search, Shield, Trash2, Users, X } from "lucide-react";
import AdminSidebar from "./AdminSidebar";
import { apiRequest } from "../../services/api";
import "./AdminUsers.css";

interface AdminUser { id:string; username?:string|null; first_name?:string|null; last_name?:string|null; email?:string|null; role?:string|null; is_active?:boolean|null; created_at?:string|null; updated_at?:string|null; }
interface AdminUsersResponse { status?:string; users?:AdminUser[]; }
interface CurrentUserResponse { status?:string; user?:{ id?:string; username?:string|null; }; }
type RoleFilter="all"|"admin"|"user";
type StatusFilter="all"|"active"|"inactive";
type SortMode="newest"|"oldest"|"name";

const getUserName=(user:AdminUser)=>[user.first_name,user.last_name].filter(Boolean).join(" ").trim()||user.username||"Unknown User";
const getInitials=(user:AdminUser)=>{const name=getUserName(user).trim().split(/\s+/);return (name.length>1?`${name[0][0]}${name[name.length-1][0]}`:name[0]?.slice(0,2)||"U").toUpperCase();};
const isAdmin=(user:AdminUser)=>user.role?.toUpperCase()==="ADMIN";
const isActive=(user:AdminUser)=>user.is_active !== false;
const formatDate=(date?:string|null)=>{if(!date)return "Unknown";const parsed=new Date(date);if(Number.isNaN(parsed.getTime()))return "Unknown";return new Intl.DateTimeFormat("en-US",{year:"numeric",month:"short",day:"numeric"}).format(parsed);};
const formatDateTime=(date?:string|null)=>{if(!date)return "Unknown";const parsed=new Date(date);if(Number.isNaN(parsed.getTime()))return "Unknown";return new Intl.DateTimeFormat("en-US",{year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(parsed);};
const getErrorMessage=(error:unknown,fallback="Unable to load users.")=>error instanceof Error&&error.message?error.message:fallback;

function AdminUsers(){
 const [users,setUsers]=useState<AdminUser[]>([]); const [currentUser,setCurrentUser]=useState<{id:string;username:string}|null>(null); const [loading,setLoading]=useState(true); const [deletingUserId,setDeletingUserId]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(""); const [roleFilter,setRoleFilter]=useState<RoleFilter>("all"); const [statusFilter,setStatusFilter]=useState<StatusFilter>("all"); const [sortMode,setSortMode]=useState<SortMode>("newest"); const [page,setPage]=useState(1); const [selectedUser,setSelectedUser]=useState<AdminUser|null>(null);
 const pageSize=10;
 const loadUsers=useCallback(async()=>{try{setLoading(true);setError(null);const [usersResult,userResult]=await Promise.all([apiRequest<AdminUsersResponse>("/api/admin/users"),apiRequest<CurrentUserResponse>("/api/user/me")]);setUsers(Array.isArray(usersResult?.users)?usersResult.users:[]);const id=userResult?.user?.id,username=userResult?.user?.username;if(id&&username)setCurrentUser({id,username});else setCurrentUser(null);}catch(err){console.error("Unable to load administrator users:",err);setError(getErrorMessage(err));}finally{setLoading(false);}},[]);
 useEffect(()=>{void loadUsers();},[loadUsers]);
 const stats=useMemo(()=>({total:users.length,active:users.filter(isActive).length,inactive:users.filter(user=>!isActive(user)).length,admins:users.filter(isAdmin).length}),[users]);
 const filteredUsers=useMemo(()=>{const term=search.trim().toLowerCase();const result=users.filter(user=>{const searchable=[getUserName(user),user.username||"",user.email||""].join(" ").toLowerCase();return(!term||searchable.includes(term))&&(roleFilter==="all"||(roleFilter==="admin"?isAdmin(user):!isAdmin(user)))&&(statusFilter==="all"||(statusFilter==="active"?isActive(user):!isActive(user)));});return [...result].sort((a,b)=>{if(sortMode==="name")return getUserName(a).localeCompare(getUserName(b));const ad=a.created_at?new Date(a.created_at).getTime():0,bd=b.created_at?new Date(b.created_at).getTime():0;return sortMode==="newest"?bd-ad:ad-bd;});},[users,search,roleFilter,statusFilter,sortMode]);
 const totalPages=Math.max(1,Math.ceil(filteredUsers.length/pageSize)); useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]); const pageUsers=filteredUsers.slice((page-1)*pageSize,page*pageSize); const hasFilters=Boolean(search.trim()||roleFilter!=="all"||statusFilter!=="all"||sortMode!=="newest");
 const resetFilters=()=>{setSearch("");setRoleFilter("all");setStatusFilter("all");setSortMode("newest");setPage(1);};
 const handleDeleteUser=async(user:AdminUser)=>{if(currentUser?.id===user.id){window.alert("You cannot delete your own administrator account.");return;}const confirmed=window.confirm(`Are you sure you want to permanently delete ${getUserName(user)}? This action cannot be undone.`);if(!confirmed)return;try{setDeletingUserId(user.id);setError(null);await apiRequest(`/api/admin/users/${user.id}`,{method:"DELETE"});setUsers(previous=>previous.filter(item=>item.id!==user.id));setSelectedUser(selectedUser?.id===user.id?null:selectedUser);}catch(err){console.error("Unable to delete user:",err);window.alert(getErrorMessage(err,"Unable to delete user."));}finally{setDeletingUserId(null);}};
 const renderRole=(user:AdminUser)=><span className={`admin-users__role ${isAdmin(user)?"admin-users__role--admin":"admin-users__role--user"}`}><Shield size={14}/>{isAdmin(user)?"Administrator":"User"}</span>;
 const renderStatus=(user:AdminUser)=><span className={`admin-users__status ${isActive(user)?"admin-users__status--active":"admin-users__status--inactive"}`}><span className="admin-users__status-dot"/>{isActive(user)?"Active":"Inactive"}</span>;
 return <div className="admin-layout"><AdminSidebar username={currentUser?.username||"Administrator"}/><main className="admin-users">
  <section className="admin-users__hero"><div className="admin-users__hero-content"><div><span className="admin-users__eyebrow">ADMINISTRATION</span><h1>Users</h1><p>Manage registered accounts, roles, and account status from one workspace.</p></div><div className="admin-users__hero-icon"><Users size={42}/></div></div></section>
  <section className="admin-users__container">
   <div className="admin-users__topbar"><div><span className="admin-users__section-label">USER MANAGEMENT</span><h2>Registered users</h2><p>{filteredUsers.length===users.length?`${users.length} accounts`:`${filteredUsers.length} of ${users.length} accounts`}</p></div><button type="button" className="admin-users__refresh" onClick={()=>void loadUsers()} disabled={loading}><RefreshCw size={17}/><span>{loading?"Refreshing":"Refresh"}</span></button></div>
   <div className="admin-users__stats"><article className="admin-users__stat admin-users__stat--primary"><span>Total users</span><strong>{stats.total}</strong><small>All registered accounts</small></article><article className="admin-users__stat"><span>Active</span><strong>{stats.active}</strong><small>Currently active</small></article><article className="admin-users__stat"><span>Inactive</span><strong>{stats.inactive}</strong><small>Inactive accounts</small></article><article className="admin-users__stat"><span>Administrators</span><strong>{stats.admins}</strong><small>Admin accounts</small></article></div>
   <div className="admin-users__filters"><label className="admin-users__search"><Search size={18}/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="Search by name, username, or email..." aria-label="Search users"/><button type="button" onClick={()=>{setSearch("");setPage(1);}} className={search?"admin-users__clear":"admin-users__clear admin-users__clear--hidden"} aria-label="Clear search"><X size={15}/></button></label><label className="admin-users__select"><span>Role</span><select value={roleFilter} onChange={event=>{setRoleFilter(event.target.value as RoleFilter);setPage(1);}}><option value="all">All roles</option><option value="admin">Administrators</option><option value="user">Users</option></select></label><label className="admin-users__select"><span>Status</span><select value={statusFilter} onChange={event=>{setStatusFilter(event.target.value as StatusFilter);setPage(1);}}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="admin-users__select"><span>Sort</span><select value={sortMode} onChange={event=>{setSortMode(event.target.value as SortMode);setPage(1);}}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name A–Z</option></select></label>{hasFilters&&<button type="button" className="admin-users__clear-filters" onClick={resetFilters}>Clear filters</button>}</div>
   {error&&!loading&&<div className="admin-users__message admin-users__message--error"><strong>Users unavailable</strong><span>{error}</span><button type="button" onClick={()=>void loadUsers()}>Try again</button></div>}
   {loading&&<div className="admin-users__loading"><span/><span/><span/><span/></div>}
   {!loading&&!error&&filteredUsers.length===0&&<div className="admin-users__empty"><Users size={28}/><strong>No users match your filters</strong><span>Try a different search or clear the filters.</span>{hasFilters&&<button type="button" onClick={resetFilters}>Clear filters</button>}</div>}
   {!loading&&!error&&filteredUsers.length>0&&<>
    <div className="admin-users__table-wrap"><table className="admin-users__table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Registered</th><th>Actions</th></tr></thead><tbody>{pageUsers.map(user=>{const mine=currentUser?.id===user.id;const deleting=deletingUserId===user.id;return <tr key={user.id} className={mine?"admin-users__row--current":""}><td><button type="button" className="admin-users__user-cell" onClick={()=>setSelectedUser(user)}><span className="admin-users__avatar">{getInitials(user)}</span><span><strong>{getUserName(user)}</strong><small>@{user.username||"unknown"}{mine&&<b>You</b>}</small></span></button></td><td><span className="admin-users__email">{user.email||"No email available"}</span></td><td>{renderRole(user)}</td><td>{renderStatus(user)}</td><td><span className="admin-users__date">{formatDate(user.created_at)}</span></td><td><div className="admin-users__row-actions"><button type="button" className="admin-users__view" onClick={()=>setSelectedUser(user)} title="View user details"><Eye size={16}/><span>View</span></button><button type="button" className="admin-users__delete-icon" onClick={()=>void handleDeleteUser(user)} disabled={mine||deleting} title={mine?"You cannot delete your own account.":"Delete user"}><Trash2 size={16}/><span>{deleting?"Deleting":"Delete"}</span></button></div></td></tr>;})}</tbody></table></div>
    <div className="admin-users__mobile-list">{pageUsers.map(user=>{const mine=currentUser?.id===user.id;const deleting=deletingUserId===user.id;return <article key={user.id} className={`admin-users__mobile-card ${mine?"admin-users__mobile-card--current":""}`}><button type="button" className="admin-users__mobile-main" onClick={()=>setSelectedUser(user)}><span className="admin-users__avatar">{getInitials(user)}</span><span className="admin-users__mobile-copy"><strong>{getUserName(user)}{mine&&<b>You</b>}</strong><small>@{user.username||"unknown"}</small><small>{user.email||"No email available"}</small></span></button><div className="admin-users__mobile-meta">{renderRole(user)}{renderStatus(user)}</div><div className="admin-users__mobile-footer"><span><Calendar size={14}/> {formatDate(user.created_at)}</span><div><button type="button" onClick={()=>setSelectedUser(user)}><Eye size={15}/> Details</button><button type="button" className="admin-users__mobile-delete" onClick={()=>void handleDeleteUser(user)} disabled={mine||deleting}><Trash2 size={15}/> {deleting?"Deleting":"Delete"}</button></div></div></article>;})}</div>
    <div className="admin-users__pagination"><span>Showing {((page-1)*pageSize)+1}–{Math.min(page*pageSize,filteredUsers.length)} of {filteredUsers.length}</span><div><button type="button" onClick={()=>setPage(value=>Math.max(1,value-1))} disabled={page===1}><ChevronLeft size={16}/></button><span>Page {page} of {totalPages}</span><button type="button" onClick={()=>setPage(value=>Math.min(totalPages,value+1))} disabled={page===totalPages}><ChevronRight size={16}/></button></div></div>
   </>}
  </section>
  {selectedUser&&<div className="admin-users__overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedUser(null);}}><aside className="admin-users__drawer" role="dialog" aria-modal="true" aria-label="User details"><div className="admin-users__drawer-head"><div><span>USER DETAILS</span><h2>Account overview</h2></div><button type="button" onClick={()=>setSelectedUser(null)} aria-label="Close details"><X size={20}/></button></div><div className="admin-users__drawer-user"><span className="admin-users__avatar admin-users__avatar--large">{getInitials(selectedUser)}</span><div><h3>{getUserName(selectedUser)}</h3><p>@{selectedUser.username||"unknown"}</p>{renderStatus(selectedUser)}</div></div><div className="admin-users__drawer-grid"><div><span>Full name</span><strong>{getUserName(selectedUser)}</strong></div><div><span>Username</span><strong>{selectedUser.username||"Unknown"}</strong></div><div><span>Email</span><strong>{selectedUser.email||"No email available"}</strong></div><div><span>Role</span><strong>{isAdmin(selectedUser)?"Administrator":"User"}</strong></div><div><span>Status</span><strong>{isActive(selectedUser)?"Active":"Inactive"}</strong></div><div><span>Registered</span><strong>{formatDateTime(selectedUser.created_at)}</strong></div><div><span>Last updated</span><strong>{formatDateTime(selectedUser.updated_at)}</strong></div><div><span>User ID</span><strong className="admin-users__drawer-id">{selectedUser.id}</strong></div></div><div className="admin-users__drawer-actions"><button type="button" className="admin-users__drawer-delete" disabled={currentUser?.id===selectedUser.id||deletingUserId===selectedUser.id} onClick={()=>void handleDeleteUser(selectedUser)}><Trash2 size={16}/>{deletingUserId===selectedUser.id?"Deleting...":"Delete user"}</button></div></aside></div>}
 </main></div>;
}
export default AdminUsers;
